// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhiwmepnpgsqiuekqrgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpoaXdtZXBucGdzcWl1ZWtxcmdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2MTY1NzcsImV4cCI6MjA1NTE5MjU3N30.u0s1zNQ2URAJH8Q2w2a5wTntM7GaVbnGqSUP7bw3wnE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);